name: alertmanager
working_dir: apps/alertmanager
compose_files: 
  - docker-compose.yml
---
name: authentik
working_dir: apps/authentik
compose_files: 
  - docker-compose.yml
---
name: dozzle
working_dir: apps/dozzle
compose_files: 
  - docker-compose.yml
---
name: frigate
working_dir: apps/frigate
compose_files: 
  - docker-compose.yml
---
name: glance
working_dir: apps/glance
compose_files: 
  - docker-compose.yml
---
name: grafana
working_dir: apps/grafana
compose_files: 
  - docker-compose.yml
---
name: gotify
working_dir: apps/gotify
compose_files: 
  - docker-compose.yml
---
name: homeassistant
working_dir: apps/homeassistant
compose_files: 
  - docker-compose.yml
---
name: mosquitto
working_dir: apps/mosquitto
compose_files: 
  - docker-compose.yml
---
name: uptimekuma
working_dir: apps/uptimekuma
compose_files: 
  - docker-compose.yml
