name: affine
working_dir: apps/affine
compose_files: 
  - docker-compose.yml
---
name: alertmanager
working_dir: apps/alertmanager
compose_files: 
  - docker-compose.yml
---
name: authentik
working_dir: apps/authentik
compose_files: 
  - docker-compose.yml
---
name: dozzle
working_dir: apps/dozzle
compose_files: 
  - docker-compose.yml
---
name: frigate
working_dir: apps/frigate
compose_files: 
  - docker-compose.yml
---
name: glance
working_dir: apps/glance
compose_files: 
  - docker-compose.yml
---
name: gotify
working_dir: apps/gotify
compose_files: 
  - docker-compose.yml
---
name: grafana
working_dir: apps/grafana
compose_files: 
  - docker-compose.yml
---
name: homeassistant
working_dir: apps/homeassistant
compose_files: 
  - docker-compose.yml
---
name: immich
working_dir: apps/immich
compose_files: 
  - docker-compose.yml
---
name: ironmount
working_dir: apps/ironmount
compose_files: 
  - docker-compose.yml
---
name: jellyfin
working_dir: apps/jellyfin
compose_files: 
  - docker-compose.yml
---
name: jellystat
working_dir: apps/jellystat
compose_files: 
  - docker-compose.yml
---
name: kavita
working_dir: apps/kavita
compose_files: 
  - docker-compose.yml
---
name: mosquitto
working_dir: apps/mosquitto
compose_files: 
  - docker-compose.yml
---
name: nextcloud
working_dir: apps/nextcloud
compose_files: 
  - docker-compose.yml
---
name: node-exporter
working_dir: apps/node-exporter
compose_files: 
  - docker-compose.yml
---
name: prometheus
working_dir: apps/prometheus
compose_files: 
  - docker-compose.yml
---
name: radarr
working_dir: apps/radarr
compose_files: 
  - docker-compose.yml
---
name: sonarr
working_dir: apps/sonarr
compose_files: 
  - docker-compose.yml
---
name: stump
working_dir: apps/stump
compose_files: 
  - docker-compose.yml
---
name: tailscale
working_dir: apps/tailscale
compose_files: 
  - docker-compose.yml
---
name: termix
working_dir: apps/termix
compose_files: 
  - docker-compose.yml
---
name: uptimekuma
working_dir: apps/uptimekuma
compose_files: 
  - docker-compose.yml
---
name: zigbee2mqtt
working_dir: apps/zigbee2mqtt
compose_files: 
  - docker-compose.yml
