creation_rules:
  # age1sdr0tx2v3apnpm9f6xz6gekz0j0xla32xp6v6sd8jpv6dhtye9xqzvxsue - Comp
  # age1dd6x6rank7eyff7kg3fhs40k8307255d07fpe5nqlu54e8ejwccscw09kx - MK-II
  # age13t99gmn3yhrzdjnhxmerue388frhrwatuj3e045lf5frxdqjputsugx7hf - Mac
  - age: >-
      age1sdr0tx2v3apnpm9f6xz6gekz0j0xla32xp6v6sd8jpv6dhtye9xqzvxsue,
      age1dd6x6rank7eyff7kg3fhs40k8307255d07fpe5nqlu54e8ejwccscw09kx,
      age13t99gmn3yhrzdjnhxmerue388frhrwatuj3e045lf5frxdqjputsugx7hf
